Reintegration of Jianping.Huang branch into trunk.
New AQFS trunk now contains package including CMAQv4.6.3 with three new changes of snow cover, windblown dust and fire smoke emissions from ARL.

diff --git a/jobs/JAQM_PREPHYB_CS b/jobs/JAQM_PREPHYB_CS
--- a/jobs/JAQM_PREPHYB_CS
+++ b/jobs/JAQM_PREPHYB_CS
@@ -12,22 +12,19 @@ export NET=aqm
 export RUN=aqm
 ############################################
 export PARAFLAG=${PARAFLAG:-NO}
-export usrdir=${usrdir:-}
-export usr_tmp=${usr_tmp:-}
-export COM_OUT=${COM_OUT:-}
 ############################################
 # obtain unique process id (pid) and make temp directories
 #####################################
 export pid=$$
-export job=aqm_prephy_conus
-export DATA=${usr_tmp}/tmpnwprd/${job}.${pid}
+export job=aqm_prephy_cs
+export DATA=${DATA:-/tmpnwprd/${job}.${pid}}
 mkdir -p $DATA
 cd $DATA 
 
 ####################################
 # File To Log Msgs
 ####################################
-export jlogfile=${usr_tmp}/com/logs/jlogfiles/jlogfile.$$
+export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${pid}}
 ####################################
 # Determine Job Output Name on System
 ####################################
@@ -43,7 +40,7 @@ export SENDCOM=YES
 export SENDDBN=YES
 export SENDECF=YES
 
-export HOMEaqm=${usrdir}/nw${envir}/cmaq.${model_ver}
+export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
 export EXECaqm=$HOMEaqm/exec
 export FIXaqm=$HOMEaqm/fix
 export USHaqm=$HOMEaqm/ush
@@ -70,11 +67,9 @@ $utilscript/setpdy.sh
 . PDY
 
 export COM=/com/${NET}/${envir}
-export COMOUT=${COM_OUT}/com/${NET}/${envir}/${RUN}.${PDY}
-#jp export COMNMM=/com/nam/${envir}/nam.${PDY}
-export COMNMM=/com/nam/prod/nam.${PDY}
-#export COMNMMm1=/com/nam/${envir}/nam.${PDYm1}
-export COMNMMm1=/com/nam/prod/nam.${PDYm1}
+export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
+export COMNMM=${COMNMM:-/com/nam/prod/nam.${PDY}}
+export COMNMMm1=${COMNMMm1:-/com/nam/prod/nam.${PDYm1}}
 
 mkdir -p $COMOUT
 
@@ -84,13 +79,13 @@ env
 # Execute the Script
 ###################################################
 ${HOMEaqm}/scripts/exaqm_prephyb_nmmb_conus.sh.ecf
-err=$?
+err=$?; err_chk
 ##################################################
 if [ "$err" != '0' ]
 then
   echo ' '
   echo '*************************************'
-  echo '*** FATAL ERROR IN CMAQ PREGEN CONUS JOB ***'
+  echo '*** FATAL ERROR IN CMAQ PREGEN CS JOB ***'
   echo '*************************************'
   echo ' '
   postmsg "ERROR IN CONUS PROGEN JOB1"
